import { useState } from "react"

function SecurityEventsPage({ securityState }) {
  const {
  aiProbability,
  riskScore,
  threatLevel,
  callId,
  callStatus,
  speakerMatch,
} = securityState
  const [expanded, setExpanded] = useState(null)

  const events = [
    {
      id: "EVT-94821",
      time: "21:53:42",
      severity: "CRITICAL",
      source: "Voice Analyzer",
      title: "Synthetic Voice Detected",
      description: "AI-generated speech characteristics detected in incoming audio.",
      score: securityState.riskScore,
      details: [
        `AI probability: ${aiProbability}%`,
        `Threat level: ${threatLevel}`,
        `Call status: ${callStatus}`, 
      ],
    },
    {
      id: "EVT-94820",
      time: "21:53:26",
      severity: "HIGH",
      source: "Speaker Verification",
      title: "Speaker Mismatch",
      description: "Incoming voice does not sufficiently match the registered speaker.",
      score: Math.max(1, securityState.riskScore - 8),
      details: [
        `Speaker status: ${
    speakerMatch === null
      ? "UNKNOWN"
      : speakerMatch
        ? "MATCH"
        : "MISMATCH"
  }`,
  "Pitch distribution anomaly detected",
  "Speaker verification confidence evaluated",
      ],
    },
    {
      id: "EVT-94819",
      time: "21:53:11",
      severity: "HIGH",
      source: "Risk Engine",
      title: "Transaction Risk Escalation",
      description: "Sensitive transaction detected during suspicious voice activity.",
      score: Math.max(1, securityState.riskScore - 14),
      details: [
        `Current risk score: ${riskScore}/100`,
  `Threat level: ${threatLevel}`,
  "Voice risk and transaction risk correlated",
      ],
    },
    {
      id: "EVT-94818",
      time: "21:52:54",
      severity: "MEDIUM",
      source: "Audio Monitor",
      title: "Audio Stream Established",
      description: "Incoming call audio stream successfully connected.",
      score: 24,
      details: [
        "Audio stream active",
        "Microphone interface connected",
        "Real-time analysis pipeline initialized",
      ],
    },
  ]

  return (
    <div className="space-y-6">

      {/* Header */}
      <div className="dashboard-card">
        <p className="text-xs uppercase tracking-[0.25em] text-cyan-400">
          VoxShield / Forensics
        </p>

        <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-4 mt-2">

          <div>
            <h1 className="text-2xl sm:text-3xl font-bold">
              Security Events
            </h1>

            <p className="text-sm text-slate-500 mt-2">
              Investigate detection events generated by the security pipeline.
            </p>
          </div>

          <div className="flex items-center gap-2 text-xs text-emerald-400">
            <span className="relative flex h-2.5 w-2.5">
              <span className="absolute inline-flex h-full w-full rounded-full bg-emerald-400 opacity-50 animate-ping" />
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-emerald-400" />
            </span>

            LIVE EVENT STREAM
          </div>

        </div>
      </div>

      {/* Investigation summary */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">

        <SummaryCard
          label="Total Events"
          value={events.length}
        />

        <SummaryCard
          label="Critical"
          value={events.filter((e) => e.severity === "CRITICAL").length}
          danger
        />

        <SummaryCard
          label="High Risk"
          value={events.filter((e) => e.severity === "HIGH").length}
          danger
        />

        <SummaryCard
          label="Current Score"
          value={securityState.riskScore}
        />

      </div>

      {/* Timeline */}
      <div className="dashboard-card rounded-2xl border border-cyan-400/10 bg-[#080f1d] p-5 sm:p-6">

        <div className="flex items-center justify-between mb-6">
          <div>
            <p className="text-xs uppercase tracking-widest text-slate-500">
              Incident Timeline
            </p>

            <h2 className="text-lg font-semibold mt-1">
              Detection Activity
            </h2>
          </div>

          <span className="text-[10px] text-slate-600 uppercase tracking-widest">
            {events.length} events
          </span>
        </div>

        <div className="space-y-3">

          {events.map((event, index) => (
            <div key={event.id}>

              <button
                onClick={() =>
                  setExpanded(
                    expanded === event.id ? null : event.id
                  )
                }
                className="w-full text-left rounded-xl border border-white/5 bg-black/20 p-4 hover:border-cyan-400/20 hover:bg-cyan-400/[0.02] transition-all duration-300"
              >

                <div className="flex gap-4">

                  {/* Timeline node */}
                  <div className="flex flex-col items-center">

                    <span
                      className={`w-3 h-3 rounded-full mt-1 ${
                        event.severity === "CRITICAL"
                          ? "bg-red-400 animate-pulse"
                          : event.severity === "HIGH"
                            ? "bg-orange-400"
                            : "bg-cyan-400"
                      }`}
                    />

                    {index !== events.length - 1 && (
                      <span className="w-px flex-1 bg-white/5 mt-2" />
                    )}

                  </div>

                  {/* Event */}
                  <div className="flex-1 min-w-0">

                    <div className="flex flex-col lg:flex-row lg:items-center lg:justify-between gap-3">

                      <div>
                        <div className="flex flex-wrap items-center gap-2">

                          <span className="font-mono text-[10px] text-cyan-400">
                            {event.id}
                          </span>

                          <span className="text-[10px] text-slate-600">
                            {event.time}
                          </span>

                        </div>

                        <h3 className="font-semibold mt-2">
                          {event.title}
                        </h3>
                      </div>

                      <div className="flex items-center gap-3">

                        <span className="text-xs text-slate-500">
                          {event.source}
                        </span>

                        <span
                          className={`px-2 py-1 rounded text-[9px] font-bold tracking-widest ${
                            event.severity === "CRITICAL"
                              ? "bg-red-400/10 text-red-400"
                              : event.severity === "HIGH"
                                ? "bg-orange-400/10 text-orange-400"
                                : "bg-cyan-400/10 text-cyan-400"
                          }`}
                        >
                          {event.severity}
                        </span>

                        <span className="text-slate-600">
                          {expanded === event.id ? "⌃" : "⌄"}
                        </span>

                      </div>

                    </div>

                    <p className="text-xs text-slate-500 mt-2">
                      {event.description}
                    </p>

                  </div>

                </div>

              </button>

              {/* Expanded details */}
              {expanded === event.id && (
                <div className="ml-7 mt-1 rounded-b-xl border border-t-0 border-white/5 bg-black/30 p-4">

                  <p className="text-[10px] uppercase tracking-widest text-cyan-400">
                    Forensic Details
                  </p>

                  <div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4">

                    {event.details.map((detail) => (
                      <div
                        key={detail}
                        className="rounded-lg border border-white/5 p-3"
                      >
                        <span className="text-xs text-slate-400">
                          {detail}
                        </span>
                      </div>
                    ))}

                  </div>

                  <div className="flex items-center justify-between mt-5 pt-4 border-t border-white/5">

                    <span className="text-[10px] uppercase tracking-widest text-slate-600">
                      Event Risk Score
                    </span>

                    <span className="font-mono font-bold text-red-400">
                      {event.score}/100
                    </span>

                  </div>

                </div>
              )}

            </div>
          ))}

        </div>
      </div>

    </div>
  )
}

function SummaryCard({ label, value, danger }) {
  return (
    <div className="dashboard-card rounded-xl border border-white/5 bg-[#080f1d] p-4">

      <p className="text-[10px] uppercase tracking-widest text-slate-500">
        {label}
      </p>

      <p
        className={`text-2xl font-bold mt-2 ${
          danger ? "text-red-400" : "text-cyan-400"
        }`}
      >
        {value}
      </p>

    </div>
  )
}

export default SecurityEventsPage